name: config
on: 
  create:
  push:
    branches:
    - main

jobs:
  config: # Test action's functionality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch Proection
      uses: infamous-riddles/branch-guardian@v1
      with: 
        PERSONAL-ACCESS-TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        BASE-BRANCH-PATTERN: '^main$'
        REQUIRED-NUMBER-OF-REVIEWERS: 1
        REQUIRED-STATUS-CHECKS: 'build-msvc, build-linux (g++), build-linux (clang++)'
        REQUIRE-REVIEW-FROM-CODEOWNERS: 'true'
        REQUIRE-LINEAR-HISTORY: 'true'
